### ISSUE TITLE
Poker Bot and Game/Game-Req Channel on Discord

### ISSUE THREAD

**Issue by Acousti** [Pemigrade/Acorn#162] opened 2020-10-03 19:10 UTC
**Brief Description**
A poker bot on discord with its own channel which could double over as a game-req channel (Possible channel name: #entertainment or #games).

**Why do you want the feature?**
The poker bot is for when people are bored and on discord. (money is not connected to ig money. Having its own channel would ensure it isn't spammed in #general or something. As Lefty said, it's basically #off-topic but more refined. The channel could also work as a channel for announcing game codes and the like for Among Us, skribbl.io, etc so it doesn't clog up #general. Similarly, there could be some kind of role that people can @ for announcing games, kind of like the sab role (so that way people can immediately see when someone is starting something up). Possible role name: @ games

**Additional context**
Here is the link for the poker bot: https://top.gg/bot/461791942779338762

**Comment by Pemigrade** [comment] 2020-10-04 01:21
Duplicate of #128, merged into it

**Closed by Pemigrade** 2020-10-04 01:21 UTC
Labels: Feature Request
