### ISSUE TITLE
KeepExp

### ISSUE THREAD

**Issue by LatteOnGithub** [Pemigrade/Acorn#113] opened 2020-07-29 17:16 UTC
**Describe the bug**
Dying to guardians, either by thorns or the laser does not keep xp after death like dying to anything else does.
The same problem has occurred by pvp once but isn't consistent.
A small bit of xp seems to be kept, this is always less than 1 level but varies.

**Expected behavior**
The exact same amount of xp and levels is kept after death.

**To Reproduce**
1. Have KeepExp from the voteshop.
2. Die to a guardian.
3. Lose xp.

**Comment by Pemigrade** [comment] 2020-07-29 18:17
Will try to replicate with default config on server with only essentials

**Comment by LatteOnGithub** [comment] 2020-07-30 13:55
Same happens with bed explosions

**Comment by Pemigrade** [comment] 2020-07-31 05:31
Able to reproduce on Acorn

**Comment by LatteOnGithub** [comment] 2020-08-07 18:20
+ fire and fall damage

**Comment by vinceingithub** [comment] 2020-08-07 18:31
I have KeepExp and none of these issues affect me, weird.

**Comment by NinOnGuthub** [comment] 2020-08-08 04:00
I also have KeepExp and these problems also happen to me both in the overworld and the nether, along with the mentioned situations it also happens when dying to drowning, suffocating, golems, skeletons, piglins, zombies and lava. 
However, you should note that this doesn't happen in the End no matter how you die

**Comment by Pemigrade** [comment] 2020-08-08 06:17
That makes sense. It looks like Essentials currently requires that keepinv is set to true for keepexp to work properly

**Comment by Pemigrade** [comment] 2020-08-08 07:09
Result of https://github.com/EbonJaeger/perworldinventory-kt/issues/180. No fix possible unfortunately, so I uninstalled PerWorldInventory. The issue should be fixed after the next restart!

**Closed by Pemigrade** 2020-08-08 07:09 UTC
Labels: Bug Report, Medium Priority
