### ISSUE TITLE
Make the @Events Team role and event luckperms group linked

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#44] opened 2020-06-30 04:18 UTC
**Brief Description**

Linking these would make it so that if you have the event group in game you'd auto get the @Events Team role when you logged on

**Why do you want the feature?**
The reasons why you want to see the feature implemented.

Needed for events team to function

**Comment by Pemigrade** [comment] 2020-06-30 05:17
Duplicate of #3

**Closed by Pemigrade** 2020-06-30 05:17 UTC
Labels: Feature Request
