### ISSUE TITLE
Have events team applications sent in #event-team-voting

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#43] opened 2020-06-30 04:16 UTC
**Brief Description**

Create a discordSRV for new ET apps to be sent in #event-team-voting on the discord

**Why do you want the feature?**
The reasons why you want to see the feature implemented.

Needed for the events team to function

**Comment by Pemigrade** [comment] 2020-06-30 05:18
Duplicate of #3

**Closed by Pemigrade** 2020-06-30 05:18 UTC
Labels: Feature Request
