### ISSUE TITLE
Add the events team application to www.acornmc.org/forms

### ISSUE THREAD

**Issue by manbrodude** [Pemigrade/Acorn#45] opened 2020-06-30 04:21 UTC
**Brief Description**

Add "**Events Team**

Submit this form to apply for the Events Team. While your application is being reviewed, do not remind staff to check your application. When we respond to your application, you will be notified either by Discord or with an in-game mail." to the website but make "this form" a hyperlink to https://forms.gle/S29y7VxiENK8otqQ7

**Why do you want the feature?**
The reasons why you want to see the feature implemented.

Needed for the events team to function

**Comment by Pemigrade** [comment] 2020-06-30 05:17
Duplicate of #3

**Closed by Pemigrade** 2020-06-30 05:17 UTC
Labels: Feature Request
