### ISSUE TITLE
Add #other/#bots on the Discord (or replace #voice with it) and add bot games

### ISSUE THREAD

**Issue by vinceingithub** [Pemigrade/Acorn#163] opened 2020-10-04 01:01 UTC
***I'm re-suggesting this because I see many people suggesting things that are very similar but much more specific.***

**Why do you want the feature?**

Currently, the discord community is lacking on the whole community aspect. At the moment, our discord server feels more like a utility than a place to hang out. While adding a bunch of bot games won't fix that problem entirely, I think it's a step in the right direction.

**Additional context**

Here's a bunch of bots to consider inviting, they have various econ/simulator/tycoon minigames and can be lots of fun.
**PLEASE NOTE: I'm not suggesting that all of or ANY OF these bots be added, they're just suggestions**

- Idle Miner: https://top.gg/bot/518759221098053634
- Gambling Bot: https://top.gg/bot/395385545326592010
- BoxBot: https://top.gg/bot/boxbot
- OwO Bot: https://top.gg/bot/owo
- Taco Shack: https://top.gg/bot/490707751832649738
- IdleRPG: https://top.gg/bot/idlerpg

**Comment by Pemigrade** [comment] 2020-10-04 01:21
Duplicate of #128

**Closed by Pemigrade** 2020-10-04 01:21 UTC
Labels: Denied, Duplicate, Feature Request
